name: Workflow1

on:
  push:
    branches:
      - main

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: v24.15.0

      - name: Run Array JS
        run: node /Users/mrandmrsgupta/Desktop/GitHubUnderstanding/File1.js

      - name: Run Array Js
        run: node /Users/mrandmrsgupta/Desktop/GitHubUnderstanding/File2.js
